package com.example

enum class AppLanguage {
    EN, TR
}

object Strings {
    private val tr = mapOf(
        "app_title" to "CINEFX",
        "app_subtitle" to "Gelişmiş Mobil Video Düzenleyici",
        "select_video" to "Bir Video Seçin",
        "select_video_desc" to "Düzenlemeye başlamak için galerinize göz atın.",
        "change_video" to "Videoyu Değiştir",
        "selected_range" to "Seçilen Aralık",
        "total_trimmed" to "Toplam Kırpılmış",
        "file" to "Dosya",
        "trim_video" to "Videoyu Kırpma",
        "start_point" to "Başlangıç Noktası",
        "end_point" to "Bitiş Noktası",
        "join_second" to "İkinci Videoyu Birleştir",
        "remove_second" to "İkinci Videoyu Kaldır",
        "select_second" to "Birleştirilecek İkinci Videoyu Seç",
        "fade_effect" to "Yumuşak Geçiş Efekti (Fade)",
        "fade_desc" to "1 saniyelik siyah ekran geçişi uygular.",
        "second_start" to "İkinci Başlangıç",
        "second_end" to "İkinci Bitiş",
        "audio_settings" to "Müzik Ekleme / Ses Ayarları",
        "mute_original" to "Orijinal Sesi Kapat",
        "mute_desc" to "Videonun kendi sesini tamamen susturur.",
        "original_volume" to "Orijinal Ses Seviyesi",
        "ducking" to "Sesi Belirli Bölümde Kıs/Ayarla",
        "ducking_desc" to "Seçilen sürede ayarlı sesi uygular, dışarıda tam ses.",
        "ducking_range" to "Kısma Aralığı",
        "add_music" to "Arka Plan Müziği Ekle",
        "music_volume" to "Müzik Sesi Seviyesi",
        "music_range_toggle" to "Müziği Sadece Belirli Bölümde Çal",
        "music_range_desc" to "Müzik sadece seçilen zaman aralığında çalar.",
        "trim_music" to "Müziği Kırp",
        "intro_title" to "Giriş Görseli (Intro) Ekle",
        "outro_title" to "Kapanış Görseli (Outro) Ekle",
        "select_image" to "Görsel Seç (Galeriden)",
        "intro_duration" to "Giriş Süresi",
        "outro_duration" to "Kapanış Süresi",
        "add_text" to "Metin Ekleme (Video Üzerine)",
        "current_text" to "Mevcut Metin",
        "text_size" to "Metin Boyutu",
        "bold" to "Kalın",
        "italic" to "Eğik",
        "rotation" to "Döndürme",
        "x_coord" to "X Koordinatı",
        "y_coord" to "Y Koordinatı",
        "entry" to "Giriş",
        "exit" to "Çıkış",
        "add_text_btn" to "Metni Ekle",
        "added_texts" to "Eklenen Metinler",
        "add_subtitle" to "Altyazı Dosyası (.SRT) Ekle",
        "select_srt" to "Altyazı (.srt) Dosyası Seç",
        "srt_active" to "altyazı öğesi aktif durumda.",
        "srt_paste" to "Alternatif: Altyazı içeriğini yapıştırabilirsiniz",
        "srt_placeholder" to "SRT Altyazı Kodları / Metni",
        "add_effect" to "Videoya Efekt Ekle",
        "add_effect_btn" to "Efekti Ekle",
        "add_filter" to "Renk Filtreleri",
        "add_filter_btn" to "Filtreyi Ekle",
        "export_video" to "Yeni Videoyu Kaydet / Aktar",
        "settings" to "Ayarlar",
        "languages" to "Diller",
        "exporting" to "Videonuz Hazırlanıyor...",
        "completing" to "İşlem Tamamlanıyor",
        "export_desc" to "Kırpma ve ses ayarlarınız uygulanıyor. Lütfen uygulamayı kapatmayın.",
        "success" to "Başarıyla Dışa Aktarıldı!",
        "success_desc" to "Düzenlenen yeni video başarıyla galerinize ve cihaz hafızasına kaydedildi.",
        "play_video" to "Videoyu Oynat",
        "share_video" to "Videoyu Paylaş",
        "close" to "Kapat",
        "error" to "Aktarım Başarısız!",
        "subtitle_color" to "Altyazı Rengi"
    )

    private val en = mapOf(
        "app_title" to "CINEFX",
        "app_subtitle" to "Advanced Mobile Video Editor",
        "select_video" to "Select a Video",
        "select_video_desc" to "Browse your gallery to start editing.",
        "change_video" to "Change Video",
        "selected_range" to "Selected Range",
        "total_trimmed" to "Total Trimmed",
        "file" to "File",
        "trim_video" to "Trim Video",
        "start_point" to "Start Point",
        "end_point" to "End Point",
        "join_second" to "Join Second Video",
        "remove_second" to "Remove Second Video",
        "select_second" to "Select Second Video to Join",
        "fade_effect" to "Fade Transition Effect",
        "fade_desc" to "Applies a 1-second black screen transition.",
        "second_start" to "Second Start",
        "second_end" to "Second End",
        "audio_settings" to "Music & Audio Settings",
        "mute_original" to "Mute Original Audio",
        "mute_desc" to "Completely mutes the video's own sound.",
        "original_volume" to "Original Volume Level",
        "ducking" to "Volume Ducking",
        "ducking_desc" to "Applies set volume during selected time, full volume outside.",
        "ducking_range" to "Ducking Range",
        "add_music" to "Add Background Music",
        "music_volume" to "Music Volume Level",
        "music_range_toggle" to "Play Music in Specific Range",
        "music_range_desc" to "Music only plays during the selected time interval.",
        "trim_music" to "Trim Music",
        "intro_title" to "Add Intro Image",
        "outro_title" to "Add Outro Image",
        "select_image" to "Select Image (from Gallery)",
        "intro_duration" to "Intro Duration",
        "outro_duration" to "Outro Duration",
        "add_text" to "Add Text (Overlay)",
        "current_text" to "Current Text",
        "text_size" to "Text Size",
        "bold" to "Bold",
        "italic" to "Italic",
        "rotation" to "Rotation",
        "x_coord" to "X Coordinate",
        "y_coord" to "Y Coordinate",
        "entry" to "Entry",
        "exit" to "Exit",
        "add_text_btn" to "Add Text",
        "added_texts" to "Added Texts",
        "add_subtitle" to "Add Subtitle File (.SRT)",
        "select_srt" to "Select Subtitle (.srt) File",
        "srt_active" to "subtitle items are active.",
        "srt_paste" to "Alternative: You can paste SRT content",
        "srt_placeholder" to "SRT Subtitle Codes / Text",
        "add_effect" to "Add Video Effect",
        "add_effect_btn" to "Add Effect",
        "add_filter" to "Color Filters",
        "add_filter_btn" to "Add Filter",
        "export_video" to "Save / Export New Video",
        "settings" to "Settings",
        "languages" to "Languages",
        "exporting" to "Preparing your video...",
        "completing" to "Completing process",
        "export_desc" to "Your trim and audio settings are being applied. Please do not close the app.",
        "success" to "Exported Successfully!",
        "success_desc" to "The newly edited video has been successfully saved to your gallery.",
        "play_video" to "Play Video",
        "share_video" to "Share Video",
        "close" to "Close",
        "error" to "Export Failed!",
        "subtitle_color" to "Subtitle Color"
    )

    fun get(key: String, lang: AppLanguage): String {
        return (if (lang == AppLanguage.TR) tr else en)[key] ?: key
    }
}
